[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_program = "31dkP6GR62uyjWCEJpbH9Ephyuj51gyR2Sfncm6tMGGj"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json" 

[scripts]
test = "cargo test"

[hooks]
